// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/contracts/authz.proto

package contracts

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StringList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringList) Reset() {
	*x = StringList{}
	mi := &file_internal_contracts_authz_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringList) ProtoMessage() {}

func (x *StringList) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_authz_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringList.ProtoReflect.Descriptor instead.
func (*StringList) Descriptor() ([]byte, []int) {
	return file_internal_contracts_authz_proto_rawDescGZIP(), []int{0}
}

func (x *StringList) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type AdapterConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Driver        string                 `protobuf:"bytes,3,opt,name=driver,proto3" json:"driver,omitempty"`
	Dsn           string                 `protobuf:"bytes,4,opt,name=dsn,proto3" json:"dsn,omitempty"`
	TableName     string                 `protobuf:"bytes,5,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	Tenant        string                 `protobuf:"bytes,6,opt,name=tenant,proto3" json:"tenant,omitempty"`
	FilterField   string                 `protobuf:"bytes,7,opt,name=filter_field,json=filterField,proto3" json:"filter_field,omitempty"`
	FilterValue   string                 `protobuf:"bytes,8,opt,name=filter_value,json=filterValue,proto3" json:"filter_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdapterConfig) Reset() {
	*x = AdapterConfig{}
	mi := &file_internal_contracts_authz_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdapterConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdapterConfig) ProtoMessage() {}

func (x *AdapterConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_authz_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdapterConfig.ProtoReflect.Descriptor instead.
func (*AdapterConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_authz_proto_rawDescGZIP(), []int{1}
}

func (x *AdapterConfig) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AdapterConfig) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *AdapterConfig) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *AdapterConfig) GetDsn() string {
	if x != nil {
		return x.Dsn
	}
	return ""
}

func (x *AdapterConfig) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *AdapterConfig) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *AdapterConfig) GetFilterField() string {
	if x != nil {
		return x.FilterField
	}
	return ""
}

func (x *AdapterConfig) GetFilterValue() string {
	if x != nil {
		return x.FilterValue
	}
	return ""
}

type WatcherConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Interval      string                 `protobuf:"bytes,2,opt,name=interval,proto3" json:"interval,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatcherConfig) Reset() {
	*x = WatcherConfig{}
	mi := &file_internal_contracts_authz_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatcherConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatcherConfig) ProtoMessage() {}

func (x *WatcherConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_authz_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatcherConfig.ProtoReflect.Descriptor instead.
func (*WatcherConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_authz_proto_rawDescGZIP(), []int{2}
}

func (x *WatcherConfig) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *WatcherConfig) GetInterval() string {
	if x != nil {
		return x.Interval
	}
	return ""
}

type CasbinModuleConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Model           string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Policies        []*StringList          `protobuf:"bytes,2,rep,name=policies,proto3" json:"policies,omitempty"`
	RoleAssignments []*StringList          `protobuf:"bytes,3,rep,name=role_assignments,json=roleAssignments,proto3" json:"role_assignments,omitempty"`
	Adapter         *AdapterConfig         `protobuf:"bytes,4,opt,name=adapter,proto3" json:"adapter,omitempty"`
	Watcher         *WatcherConfig         `protobuf:"bytes,5,opt,name=watcher,proto3" json:"watcher,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CasbinModuleConfig) Reset() {
	*x = CasbinModuleConfig{}
	mi := &file_internal_contracts_authz_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CasbinModuleConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CasbinModuleConfig) ProtoMessage() {}

func (x *CasbinModuleConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_authz_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CasbinModuleConfig.ProtoReflect.Descriptor instead.
func (*CasbinModuleConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_authz_proto_rawDescGZIP(), []int{3}
}

func (x *CasbinModuleConfig) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CasbinModuleConfig) GetPolicies() []*StringList {
	if x != nil {
		return x.Policies
	}
	return nil
}

func (x *CasbinModuleConfig) GetRoleAssignments() []*StringList {
	if x != nil {
		return x.RoleAssignments
	}
	return nil
}

func (x *CasbinModuleConfig) GetAdapter() *AdapterConfig {
	if x != nil {
		return x.Adapter
	}
	return nil
}

func (x *CasbinModuleConfig) GetWatcher() *WatcherConfig {
	if x != nil {
		return x.Watcher
	}
	return nil
}

type PermitModuleConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	PdpUrl        string                 `protobuf:"bytes,2,opt,name=pdp_url,json=pdpUrl,proto3" json:"pdp_url,omitempty"`
	ApiUrl        string                 `protobuf:"bytes,3,opt,name=api_url,json=apiUrl,proto3" json:"api_url,omitempty"`
	Project       string                 `protobuf:"bytes,4,opt,name=project,proto3" json:"project,omitempty"`
	Environment   string                 `protobuf:"bytes,5,opt,name=environment,proto3" json:"environment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermitModuleConfig) Reset() {
	*x = PermitModuleConfig{}
	mi := &file_internal_contracts_authz_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermitModuleConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermitModuleConfig) ProtoMessage() {}

func (x *PermitModuleConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_authz_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermitModuleConfig.ProtoReflect.Descriptor instead.
func (*PermitModuleConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_authz_proto_rawDescGZIP(), []int{4}
}

func (x *PermitModuleConfig) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *PermitModuleConfig) GetPdpUrl() string {
	if x != nil {
		return x.PdpUrl
	}
	return ""
}

func (x *PermitModuleConfig) GetApiUrl() string {
	if x != nil {
		return x.ApiUrl
	}
	return ""
}

func (x *PermitModuleConfig) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *PermitModuleConfig) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

type ExtraField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtraField) Reset() {
	*x = ExtraField{}
	mi := &file_internal_contracts_authz_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtraField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtraField) ProtoMessage() {}

func (x *ExtraField) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_authz_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtraField.ProtoReflect.Descriptor instead.
func (*ExtraField) Descriptor() ([]byte, []int) {
	return file_internal_contracts_authz_proto_rawDescGZIP(), []int{5}
}

func (x *ExtraField) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ExtraField) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type AuthzCheckConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Module        string                 `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	SubjectKey    string                 `protobuf:"bytes,2,opt,name=subject_key,json=subjectKey,proto3" json:"subject_key,omitempty"`
	Object        string                 `protobuf:"bytes,3,opt,name=object,proto3" json:"object,omitempty"`
	Action        string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	Audit         bool                   `protobuf:"varint,5,opt,name=audit,proto3" json:"audit,omitempty"`
	ExtraFields   []*ExtraField          `protobuf:"bytes,6,rep,name=extra_fields,json=extraFields,proto3" json:"extra_fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthzCheckConfig) Reset() {
	*x = AuthzCheckConfig{}
	mi := &file_internal_contracts_authz_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthzCheckConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthzCheckConfig) ProtoMessage() {}

func (x *AuthzCheckConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_authz_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthzCheckConfig.ProtoReflect.Descriptor instead.
func (*AuthzCheckConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_authz_proto_rawDescGZIP(), []int{6}
}

func (x *AuthzCheckConfig) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *AuthzCheckConfig) GetSubjectKey() string {
	if x != nil {
		return x.SubjectKey
	}
	return ""
}

func (x *AuthzCheckConfig) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *AuthzCheckConfig) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AuthzCheckConfig) GetAudit() bool {
	if x != nil {
		return x.Audit
	}
	return false
}

func (x *AuthzCheckConfig) GetExtraFields() []*ExtraField {
	if x != nil {
		return x.ExtraFields
	}
	return nil
}

type AuthzCheckInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Module        string                 `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	SubjectKey    string                 `protobuf:"bytes,2,opt,name=subject_key,json=subjectKey,proto3" json:"subject_key,omitempty"`
	Subject       string                 `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	Object        string                 `protobuf:"bytes,4,opt,name=object,proto3" json:"object,omitempty"`
	Action        string                 `protobuf:"bytes,5,opt,name=action,proto3" json:"action,omitempty"`
	ExtraFields   []*ExtraField          `protobuf:"bytes,6,rep,name=extra_fields,json=extraFields,proto3" json:"extra_fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthzCheckInput) Reset() {
	*x = AuthzCheckInput{}
	mi := &file_internal_contracts_authz_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthzCheckInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthzCheckInput) ProtoMessage() {}

func (x *AuthzCheckInput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_authz_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthzCheckInput.ProtoReflect.Descriptor instead.
func (*AuthzCheckInput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_authz_proto_rawDescGZIP(), []int{7}
}

func (x *AuthzCheckInput) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *AuthzCheckInput) GetSubjectKey() string {
	if x != nil {
		return x.SubjectKey
	}
	return ""
}

func (x *AuthzCheckInput) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *AuthzCheckInput) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *AuthzCheckInput) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AuthzCheckInput) GetExtraFields() []*ExtraField {
	if x != nil {
		return x.ExtraFields
	}
	return nil
}

type AuthzCheckOutput struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Subject         string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Object          string                 `protobuf:"bytes,2,opt,name=object,proto3" json:"object,omitempty"`
	Action          string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	Allowed         bool                   `protobuf:"varint,4,opt,name=allowed,proto3" json:"allowed,omitempty"`
	ResponseStatus  int32                  `protobuf:"varint,5,opt,name=response_status,json=responseStatus,proto3" json:"response_status,omitempty"`
	ResponseBody    string                 `protobuf:"bytes,6,opt,name=response_body,json=responseBody,proto3" json:"response_body,omitempty"`
	ResponseHeaders *structpb.Struct       `protobuf:"bytes,7,opt,name=response_headers,json=responseHeaders,proto3" json:"response_headers,omitempty"`
	Error           string                 `protobuf:"bytes,100,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AuthzCheckOutput) Reset() {
	*x = AuthzCheckOutput{}
	mi := &file_internal_contracts_authz_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthzCheckOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthzCheckOutput) ProtoMessage() {}

func (x *AuthzCheckOutput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_authz_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthzCheckOutput.ProtoReflect.Descriptor instead.
func (*AuthzCheckOutput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_authz_proto_rawDescGZIP(), []int{8}
}

func (x *AuthzCheckOutput) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *AuthzCheckOutput) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *AuthzCheckOutput) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AuthzCheckOutput) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *AuthzCheckOutput) GetResponseStatus() int32 {
	if x != nil {
		return x.ResponseStatus
	}
	return 0
}

func (x *AuthzCheckOutput) GetResponseBody() string {
	if x != nil {
		return x.ResponseBody
	}
	return ""
}

func (x *AuthzCheckOutput) GetResponseHeaders() *structpb.Struct {
	if x != nil {
		return x.ResponseHeaders
	}
	return nil
}

func (x *AuthzCheckOutput) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type PolicyRuleConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Module        string                 `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	Rule          []string               `protobuf:"bytes,2,rep,name=rule,proto3" json:"rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyRuleConfig) Reset() {
	*x = PolicyRuleConfig{}
	mi := &file_internal_contracts_authz_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyRuleConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyRuleConfig) ProtoMessage() {}

func (x *PolicyRuleConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_authz_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyRuleConfig.ProtoReflect.Descriptor instead.
func (*PolicyRuleConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_authz_proto_rawDescGZIP(), []int{9}
}

func (x *PolicyRuleConfig) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *PolicyRuleConfig) GetRule() []string {
	if x != nil {
		return x.Rule
	}
	return nil
}

type PolicyRuleInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Module        string                 `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	Rule          []string               `protobuf:"bytes,2,rep,name=rule,proto3" json:"rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyRuleInput) Reset() {
	*x = PolicyRuleInput{}
	mi := &file_internal_contracts_authz_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyRuleInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyRuleInput) ProtoMessage() {}

func (x *PolicyRuleInput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_authz_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyRuleInput.ProtoReflect.Descriptor instead.
func (*PolicyRuleInput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_authz_proto_rawDescGZIP(), []int{10}
}

func (x *PolicyRuleInput) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *PolicyRuleInput) GetRule() []string {
	if x != nil {
		return x.Rule
	}
	return nil
}

type PolicyRuleOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Changed       bool                   `protobuf:"varint,1,opt,name=changed,proto3" json:"changed,omitempty"`
	Rule          []string               `protobuf:"bytes,2,rep,name=rule,proto3" json:"rule,omitempty"`
	Error         string                 `protobuf:"bytes,100,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyRuleOutput) Reset() {
	*x = PolicyRuleOutput{}
	mi := &file_internal_contracts_authz_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyRuleOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyRuleOutput) ProtoMessage() {}

func (x *PolicyRuleOutput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_authz_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyRuleOutput.ProtoReflect.Descriptor instead.
func (*PolicyRuleOutput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_authz_proto_rawDescGZIP(), []int{11}
}

func (x *PolicyRuleOutput) GetChanged() bool {
	if x != nil {
		return x.Changed
	}
	return false
}

func (x *PolicyRuleOutput) GetRule() []string {
	if x != nil {
		return x.Rule
	}
	return nil
}

func (x *PolicyRuleOutput) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RoleAssignConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Module        string                 `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Assignments   []*StringList          `protobuf:"bytes,3,rep,name=assignments,proto3" json:"assignments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleAssignConfig) Reset() {
	*x = RoleAssignConfig{}
	mi := &file_internal_contracts_authz_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleAssignConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleAssignConfig) ProtoMessage() {}

func (x *RoleAssignConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_authz_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleAssignConfig.ProtoReflect.Descriptor instead.
func (*RoleAssignConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_authz_proto_rawDescGZIP(), []int{12}
}

func (x *RoleAssignConfig) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *RoleAssignConfig) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *RoleAssignConfig) GetAssignments() []*StringList {
	if x != nil {
		return x.Assignments
	}
	return nil
}

type RoleAssignInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Module        string                 `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Assignments   []*StringList          `protobuf:"bytes,3,rep,name=assignments,proto3" json:"assignments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleAssignInput) Reset() {
	*x = RoleAssignInput{}
	mi := &file_internal_contracts_authz_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleAssignInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleAssignInput) ProtoMessage() {}

func (x *RoleAssignInput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_authz_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleAssignInput.ProtoReflect.Descriptor instead.
func (*RoleAssignInput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_authz_proto_rawDescGZIP(), []int{13}
}

func (x *RoleAssignInput) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *RoleAssignInput) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *RoleAssignInput) GetAssignments() []*StringList {
	if x != nil {
		return x.Assignments
	}
	return nil
}

type RoleAssignOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	Assignments   []*StringList          `protobuf:"bytes,2,rep,name=assignments,proto3" json:"assignments,omitempty"`
	Error         string                 `protobuf:"bytes,100,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleAssignOutput) Reset() {
	*x = RoleAssignOutput{}
	mi := &file_internal_contracts_authz_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleAssignOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleAssignOutput) ProtoMessage() {}

func (x *RoleAssignOutput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_authz_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleAssignOutput.ProtoReflect.Descriptor instead.
func (*RoleAssignOutput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_authz_proto_rawDescGZIP(), []int{14}
}

func (x *RoleAssignOutput) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *RoleAssignOutput) GetAssignments() []*StringList {
	if x != nil {
		return x.Assignments
	}
	return nil
}

func (x *RoleAssignOutput) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CapabilitiesConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Module        string                 `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	Provider      string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilitiesConfig) Reset() {
	*x = CapabilitiesConfig{}
	mi := &file_internal_contracts_authz_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesConfig) ProtoMessage() {}

func (x *CapabilitiesConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_authz_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesConfig.ProtoReflect.Descriptor instead.
func (*CapabilitiesConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_authz_proto_rawDescGZIP(), []int{15}
}

func (x *CapabilitiesConfig) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *CapabilitiesConfig) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

type CapabilitiesInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Module        string                 `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	Provider      string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilitiesInput) Reset() {
	*x = CapabilitiesInput{}
	mi := &file_internal_contracts_authz_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesInput) ProtoMessage() {}

func (x *CapabilitiesInput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_authz_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesInput.ProtoReflect.Descriptor instead.
func (*CapabilitiesInput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_authz_proto_rawDescGZIP(), []int{16}
}

func (x *CapabilitiesInput) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *CapabilitiesInput) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

type CapabilitiesOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Module        string                 `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	Provider      string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	Capabilities  []string               `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Error         string                 `protobuf:"bytes,100,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilitiesOutput) Reset() {
	*x = CapabilitiesOutput{}
	mi := &file_internal_contracts_authz_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesOutput) ProtoMessage() {}

func (x *CapabilitiesOutput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_authz_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesOutput.ProtoReflect.Descriptor instead.
func (*CapabilitiesOutput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_authz_proto_rawDescGZIP(), []int{17}
}

func (x *CapabilitiesOutput) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *CapabilitiesOutput) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *CapabilitiesOutput) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *CapabilitiesOutput) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SubjectObjectActionConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Module        string                 `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Object        string                 `protobuf:"bytes,3,opt,name=object,proto3" json:"object,omitempty"`
	Action        string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubjectObjectActionConfig) Reset() {
	*x = SubjectObjectActionConfig{}
	mi := &file_internal_contracts_authz_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubjectObjectActionConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubjectObjectActionConfig) ProtoMessage() {}

func (x *SubjectObjectActionConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_authz_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubjectObjectActionConfig.ProtoReflect.Descriptor instead.
func (*SubjectObjectActionConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_authz_proto_rawDescGZIP(), []int{18}
}

func (x *SubjectObjectActionConfig) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *SubjectObjectActionConfig) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *SubjectObjectActionConfig) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *SubjectObjectActionConfig) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type SubjectObjectActionInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Module        string                 `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Object        string                 `protobuf:"bytes,3,opt,name=object,proto3" json:"object,omitempty"`
	Action        string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubjectObjectActionInput) Reset() {
	*x = SubjectObjectActionInput{}
	mi := &file_internal_contracts_authz_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubjectObjectActionInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubjectObjectActionInput) ProtoMessage() {}

func (x *SubjectObjectActionInput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_authz_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubjectObjectActionInput.ProtoReflect.Descriptor instead.
func (*SubjectObjectActionInput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_authz_proto_rawDescGZIP(), []int{19}
}

func (x *SubjectObjectActionInput) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *SubjectObjectActionInput) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *SubjectObjectActionInput) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *SubjectObjectActionInput) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type SubjectObjectActionOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Changed       bool                   `protobuf:"varint,2,opt,name=changed,proto3" json:"changed,omitempty"`
	Subject       string                 `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	Object        string                 `protobuf:"bytes,4,opt,name=object,proto3" json:"object,omitempty"`
	Action        string                 `protobuf:"bytes,5,opt,name=action,proto3" json:"action,omitempty"`
	Error         string                 `protobuf:"bytes,100,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubjectObjectActionOutput) Reset() {
	*x = SubjectObjectActionOutput{}
	mi := &file_internal_contracts_authz_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubjectObjectActionOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubjectObjectActionOutput) ProtoMessage() {}

func (x *SubjectObjectActionOutput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_authz_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubjectObjectActionOutput.ProtoReflect.Descriptor instead.
func (*SubjectObjectActionOutput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_authz_proto_rawDescGZIP(), []int{20}
}

func (x *SubjectObjectActionOutput) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *SubjectObjectActionOutput) GetChanged() bool {
	if x != nil {
		return x.Changed
	}
	return false
}

func (x *SubjectObjectActionOutput) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *SubjectObjectActionOutput) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *SubjectObjectActionOutput) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *SubjectObjectActionOutput) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ListConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Module        string                 `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	Filter        string                 `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConfig) Reset() {
	*x = ListConfig{}
	mi := &file_internal_contracts_authz_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConfig) ProtoMessage() {}

func (x *ListConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_authz_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConfig.ProtoReflect.Descriptor instead.
func (*ListConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_authz_proto_rawDescGZIP(), []int{21}
}

func (x *ListConfig) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *ListConfig) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *ListConfig) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ListInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Module        string                 `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	Filter        string                 `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInput) Reset() {
	*x = ListInput{}
	mi := &file_internal_contracts_authz_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInput) ProtoMessage() {}

func (x *ListInput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_authz_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInput.ProtoReflect.Descriptor instead.
func (*ListInput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_authz_proto_rawDescGZIP(), []int{22}
}

func (x *ListInput) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *ListInput) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *ListInput) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type GenericStepOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        *structpb.Struct       `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                 `protobuf:"bytes,100,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenericStepOutput) Reset() {
	*x = GenericStepOutput{}
	mi := &file_internal_contracts_authz_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenericStepOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenericStepOutput) ProtoMessage() {}

func (x *GenericStepOutput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_authz_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenericStepOutput.ProtoReflect.Descriptor instead.
func (*GenericStepOutput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_authz_proto_rawDescGZIP(), []int{23}
}

func (x *GenericStepOutput) GetOutput() *structpb.Struct {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *GenericStepOutput) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RelationConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Module        string                 `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Relation      string                 `protobuf:"bytes,3,opt,name=relation,proto3" json:"relation,omitempty"`
	Object        string                 `protobuf:"bytes,4,opt,name=object,proto3" json:"object,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelationConfig) Reset() {
	*x = RelationConfig{}
	mi := &file_internal_contracts_authz_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelationConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationConfig) ProtoMessage() {}

func (x *RelationConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_authz_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationConfig.ProtoReflect.Descriptor instead.
func (*RelationConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_authz_proto_rawDescGZIP(), []int{24}
}

func (x *RelationConfig) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *RelationConfig) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *RelationConfig) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *RelationConfig) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

type RelationInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Module        string                 `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Relation      string                 `protobuf:"bytes,3,opt,name=relation,proto3" json:"relation,omitempty"`
	Object        string                 `protobuf:"bytes,4,opt,name=object,proto3" json:"object,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelationInput) Reset() {
	*x = RelationInput{}
	mi := &file_internal_contracts_authz_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelationInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationInput) ProtoMessage() {}

func (x *RelationInput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_authz_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationInput.ProtoReflect.Descriptor instead.
func (*RelationInput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_authz_proto_rawDescGZIP(), []int{25}
}

func (x *RelationInput) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *RelationInput) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *RelationInput) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *RelationInput) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

type RelationOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Changed       bool                   `protobuf:"varint,1,opt,name=changed,proto3" json:"changed,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Relation      string                 `protobuf:"bytes,3,opt,name=relation,proto3" json:"relation,omitempty"`
	Object        string                 `protobuf:"bytes,4,opt,name=object,proto3" json:"object,omitempty"`
	Error         string                 `protobuf:"bytes,100,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelationOutput) Reset() {
	*x = RelationOutput{}
	mi := &file_internal_contracts_authz_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelationOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationOutput) ProtoMessage() {}

func (x *RelationOutput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_authz_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationOutput.ProtoReflect.Descriptor instead.
func (*RelationOutput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_authz_proto_rawDescGZIP(), []int{26}
}

func (x *RelationOutput) GetChanged() bool {
	if x != nil {
		return x.Changed
	}
	return false
}

func (x *RelationOutput) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *RelationOutput) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *RelationOutput) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *RelationOutput) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type PermitStepConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Module        string                 `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	Values        *structpb.Struct       `protobuf:"bytes,2,opt,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermitStepConfig) Reset() {
	*x = PermitStepConfig{}
	mi := &file_internal_contracts_authz_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermitStepConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermitStepConfig) ProtoMessage() {}

func (x *PermitStepConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_authz_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermitStepConfig.ProtoReflect.Descriptor instead.
func (*PermitStepConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_authz_proto_rawDescGZIP(), []int{27}
}

func (x *PermitStepConfig) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *PermitStepConfig) GetValues() *structpb.Struct {
	if x != nil {
		return x.Values
	}
	return nil
}

type PermitStepInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Module        string                 `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	Values        *structpb.Struct       `protobuf:"bytes,2,opt,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermitStepInput) Reset() {
	*x = PermitStepInput{}
	mi := &file_internal_contracts_authz_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermitStepInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermitStepInput) ProtoMessage() {}

func (x *PermitStepInput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_authz_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermitStepInput.ProtoReflect.Descriptor instead.
func (*PermitStepInput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_authz_proto_rawDescGZIP(), []int{28}
}

func (x *PermitStepInput) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *PermitStepInput) GetValues() *structpb.Struct {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_internal_contracts_authz_proto protoreflect.FileDescriptor

const file_internal_contracts_authz_proto_rawDesc = "" +
	"\n" +
	"\x1einternal/contracts/authz.proto\x12\x19workflow.plugins.authz.v1\x1a\x1cgoogle/protobuf/struct.proto\"$\n" +
	"\n" +
	"StringList\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"\xde\x01\n" +
	"\rAdapterConfig\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x16\n" +
	"\x06driver\x18\x03 \x01(\tR\x06driver\x12\x10\n" +
	"\x03dsn\x18\x04 \x01(\tR\x03dsn\x12\x1d\n" +
	"\n" +
	"table_name\x18\x05 \x01(\tR\ttableName\x12\x16\n" +
	"\x06tenant\x18\x06 \x01(\tR\x06tenant\x12!\n" +
	"\ffilter_field\x18\a \x01(\tR\vfilterField\x12!\n" +
	"\ffilter_value\x18\b \x01(\tR\vfilterValue\"?\n" +
	"\rWatcherConfig\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1a\n" +
	"\binterval\x18\x02 \x01(\tR\binterval\"\xc7\x02\n" +
	"\x12CasbinModuleConfig\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12A\n" +
	"\bpolicies\x18\x02 \x03(\v2%.workflow.plugins.authz.v1.StringListR\bpolicies\x12P\n" +
	"\x10role_assignments\x18\x03 \x03(\v2%.workflow.plugins.authz.v1.StringListR\x0froleAssignments\x12B\n" +
	"\aadapter\x18\x04 \x01(\v2(.workflow.plugins.authz.v1.AdapterConfigR\aadapter\x12B\n" +
	"\awatcher\x18\x05 \x01(\v2(.workflow.plugins.authz.v1.WatcherConfigR\awatcher\"\x9b\x01\n" +
	"\x12PermitModuleConfig\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x17\n" +
	"\apdp_url\x18\x02 \x01(\tR\x06pdpUrl\x12\x17\n" +
	"\aapi_url\x18\x03 \x01(\tR\x06apiUrl\x12\x18\n" +
	"\aproject\x18\x04 \x01(\tR\aproject\x12 \n" +
	"\venvironment\x18\x05 \x01(\tR\venvironment\"4\n" +
	"\n" +
	"ExtraField\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xdb\x01\n" +
	"\x10AuthzCheckConfig\x12\x16\n" +
	"\x06module\x18\x01 \x01(\tR\x06module\x12\x1f\n" +
	"\vsubject_key\x18\x02 \x01(\tR\n" +
	"subjectKey\x12\x16\n" +
	"\x06object\x18\x03 \x01(\tR\x06object\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x12\x14\n" +
	"\x05audit\x18\x05 \x01(\bR\x05audit\x12H\n" +
	"\fextra_fields\x18\x06 \x03(\v2%.workflow.plugins.authz.v1.ExtraFieldR\vextraFields\"\xde\x01\n" +
	"\x0fAuthzCheckInput\x12\x16\n" +
	"\x06module\x18\x01 \x01(\tR\x06module\x12\x1f\n" +
	"\vsubject_key\x18\x02 \x01(\tR\n" +
	"subjectKey\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\x12\x16\n" +
	"\x06object\x18\x04 \x01(\tR\x06object\x12\x16\n" +
	"\x06action\x18\x05 \x01(\tR\x06action\x12H\n" +
	"\fextra_fields\x18\x06 \x03(\v2%.workflow.plugins.authz.v1.ExtraFieldR\vextraFields\"\x9e\x02\n" +
	"\x10AuthzCheckOutput\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x16\n" +
	"\x06object\x18\x02 \x01(\tR\x06object\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12\x18\n" +
	"\aallowed\x18\x04 \x01(\bR\aallowed\x12'\n" +
	"\x0fresponse_status\x18\x05 \x01(\x05R\x0eresponseStatus\x12#\n" +
	"\rresponse_body\x18\x06 \x01(\tR\fresponseBody\x12B\n" +
	"\x10response_headers\x18\a \x01(\v2\x17.google.protobuf.StructR\x0fresponseHeaders\x12\x14\n" +
	"\x05error\x18d \x01(\tR\x05error\">\n" +
	"\x10PolicyRuleConfig\x12\x16\n" +
	"\x06module\x18\x01 \x01(\tR\x06module\x12\x12\n" +
	"\x04rule\x18\x02 \x03(\tR\x04rule\"=\n" +
	"\x0fPolicyRuleInput\x12\x16\n" +
	"\x06module\x18\x01 \x01(\tR\x06module\x12\x12\n" +
	"\x04rule\x18\x02 \x03(\tR\x04rule\"V\n" +
	"\x10PolicyRuleOutput\x12\x18\n" +
	"\achanged\x18\x01 \x01(\bR\achanged\x12\x12\n" +
	"\x04rule\x18\x02 \x03(\tR\x04rule\x12\x14\n" +
	"\x05error\x18d \x01(\tR\x05error\"\x8b\x01\n" +
	"\x10RoleAssignConfig\x12\x16\n" +
	"\x06module\x18\x01 \x01(\tR\x06module\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12G\n" +
	"\vassignments\x18\x03 \x03(\v2%.workflow.plugins.authz.v1.StringListR\vassignments\"\x8a\x01\n" +
	"\x0fRoleAssignInput\x12\x16\n" +
	"\x06module\x18\x01 \x01(\tR\x06module\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12G\n" +
	"\vassignments\x18\x03 \x03(\v2%.workflow.plugins.authz.v1.StringListR\vassignments\"\x89\x01\n" +
	"\x10RoleAssignOutput\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12G\n" +
	"\vassignments\x18\x02 \x03(\v2%.workflow.plugins.authz.v1.StringListR\vassignments\x12\x14\n" +
	"\x05error\x18d \x01(\tR\x05error\"H\n" +
	"\x12CapabilitiesConfig\x12\x16\n" +
	"\x06module\x18\x01 \x01(\tR\x06module\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\"G\n" +
	"\x11CapabilitiesInput\x12\x16\n" +
	"\x06module\x18\x01 \x01(\tR\x06module\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\"\x82\x01\n" +
	"\x12CapabilitiesOutput\x12\x16\n" +
	"\x06module\x18\x01 \x01(\tR\x06module\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12\"\n" +
	"\fcapabilities\x18\x03 \x03(\tR\fcapabilities\x12\x14\n" +
	"\x05error\x18d \x01(\tR\x05error\"}\n" +
	"\x19SubjectObjectActionConfig\x12\x16\n" +
	"\x06module\x18\x01 \x01(\tR\x06module\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x16\n" +
	"\x06object\x18\x03 \x01(\tR\x06object\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\"|\n" +
	"\x18SubjectObjectActionInput\x12\x16\n" +
	"\x06module\x18\x01 \x01(\tR\x06module\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x16\n" +
	"\x06object\x18\x03 \x01(\tR\x06object\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\"\xaf\x01\n" +
	"\x19SubjectObjectActionOutput\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x18\n" +
	"\achanged\x18\x02 \x01(\bR\achanged\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\x12\x16\n" +
	"\x06object\x18\x04 \x01(\tR\x06object\x12\x16\n" +
	"\x06action\x18\x05 \x01(\tR\x06action\x12\x14\n" +
	"\x05error\x18d \x01(\tR\x05error\"R\n" +
	"\n" +
	"ListConfig\x12\x16\n" +
	"\x06module\x18\x01 \x01(\tR\x06module\x12\x16\n" +
	"\x06filter\x18\x02 \x01(\tR\x06filter\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"Q\n" +
	"\tListInput\x12\x16\n" +
	"\x06module\x18\x01 \x01(\tR\x06module\x12\x16\n" +
	"\x06filter\x18\x02 \x01(\tR\x06filter\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"Z\n" +
	"\x11GenericStepOutput\x12/\n" +
	"\x06output\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x06output\x12\x14\n" +
	"\x05error\x18d \x01(\tR\x05error\"v\n" +
	"\x0eRelationConfig\x12\x16\n" +
	"\x06module\x18\x01 \x01(\tR\x06module\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x1a\n" +
	"\brelation\x18\x03 \x01(\tR\brelation\x12\x16\n" +
	"\x06object\x18\x04 \x01(\tR\x06object\"u\n" +
	"\rRelationInput\x12\x16\n" +
	"\x06module\x18\x01 \x01(\tR\x06module\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x1a\n" +
	"\brelation\x18\x03 \x01(\tR\brelation\x12\x16\n" +
	"\x06object\x18\x04 \x01(\tR\x06object\"\x8e\x01\n" +
	"\x0eRelationOutput\x12\x18\n" +
	"\achanged\x18\x01 \x01(\bR\achanged\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x1a\n" +
	"\brelation\x18\x03 \x01(\tR\brelation\x12\x16\n" +
	"\x06object\x18\x04 \x01(\tR\x06object\x12\x14\n" +
	"\x05error\x18d \x01(\tR\x05error\"[\n" +
	"\x10PermitStepConfig\x12\x16\n" +
	"\x06module\x18\x01 \x01(\tR\x06module\x12/\n" +
	"\x06values\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x06values\"Z\n" +
	"\x0fPermitStepInput\x12\x16\n" +
	"\x06module\x18\x01 \x01(\tR\x06module\x12/\n" +
	"\x06values\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x06valuesBAZ?github.com/GoCodeAlone/workflow-plugin-authz/internal/contractsb\x06proto3"

var (
	file_internal_contracts_authz_proto_rawDescOnce sync.Once
	file_internal_contracts_authz_proto_rawDescData []byte
)

func file_internal_contracts_authz_proto_rawDescGZIP() []byte {
	file_internal_contracts_authz_proto_rawDescOnce.Do(func() {
		file_internal_contracts_authz_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_contracts_authz_proto_rawDesc), len(file_internal_contracts_authz_proto_rawDesc)))
	})
	return file_internal_contracts_authz_proto_rawDescData
}

var file_internal_contracts_authz_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_internal_contracts_authz_proto_goTypes = []any{
	(*StringList)(nil),                // 0: workflow.plugins.authz.v1.StringList
	(*AdapterConfig)(nil),             // 1: workflow.plugins.authz.v1.AdapterConfig
	(*WatcherConfig)(nil),             // 2: workflow.plugins.authz.v1.WatcherConfig
	(*CasbinModuleConfig)(nil),        // 3: workflow.plugins.authz.v1.CasbinModuleConfig
	(*PermitModuleConfig)(nil),        // 4: workflow.plugins.authz.v1.PermitModuleConfig
	(*ExtraField)(nil),                // 5: workflow.plugins.authz.v1.ExtraField
	(*AuthzCheckConfig)(nil),          // 6: workflow.plugins.authz.v1.AuthzCheckConfig
	(*AuthzCheckInput)(nil),           // 7: workflow.plugins.authz.v1.AuthzCheckInput
	(*AuthzCheckOutput)(nil),          // 8: workflow.plugins.authz.v1.AuthzCheckOutput
	(*PolicyRuleConfig)(nil),          // 9: workflow.plugins.authz.v1.PolicyRuleConfig
	(*PolicyRuleInput)(nil),           // 10: workflow.plugins.authz.v1.PolicyRuleInput
	(*PolicyRuleOutput)(nil),          // 11: workflow.plugins.authz.v1.PolicyRuleOutput
	(*RoleAssignConfig)(nil),          // 12: workflow.plugins.authz.v1.RoleAssignConfig
	(*RoleAssignInput)(nil),           // 13: workflow.plugins.authz.v1.RoleAssignInput
	(*RoleAssignOutput)(nil),          // 14: workflow.plugins.authz.v1.RoleAssignOutput
	(*CapabilitiesConfig)(nil),        // 15: workflow.plugins.authz.v1.CapabilitiesConfig
	(*CapabilitiesInput)(nil),         // 16: workflow.plugins.authz.v1.CapabilitiesInput
	(*CapabilitiesOutput)(nil),        // 17: workflow.plugins.authz.v1.CapabilitiesOutput
	(*SubjectObjectActionConfig)(nil), // 18: workflow.plugins.authz.v1.SubjectObjectActionConfig
	(*SubjectObjectActionInput)(nil),  // 19: workflow.plugins.authz.v1.SubjectObjectActionInput
	(*SubjectObjectActionOutput)(nil), // 20: workflow.plugins.authz.v1.SubjectObjectActionOutput
	(*ListConfig)(nil),                // 21: workflow.plugins.authz.v1.ListConfig
	(*ListInput)(nil),                 // 22: workflow.plugins.authz.v1.ListInput
	(*GenericStepOutput)(nil),         // 23: workflow.plugins.authz.v1.GenericStepOutput
	(*RelationConfig)(nil),            // 24: workflow.plugins.authz.v1.RelationConfig
	(*RelationInput)(nil),             // 25: workflow.plugins.authz.v1.RelationInput
	(*RelationOutput)(nil),            // 26: workflow.plugins.authz.v1.RelationOutput
	(*PermitStepConfig)(nil),          // 27: workflow.plugins.authz.v1.PermitStepConfig
	(*PermitStepInput)(nil),           // 28: workflow.plugins.authz.v1.PermitStepInput
	(*structpb.Struct)(nil),           // 29: google.protobuf.Struct
}
var file_internal_contracts_authz_proto_depIdxs = []int32{
	0,  // 0: workflow.plugins.authz.v1.CasbinModuleConfig.policies:type_name -> workflow.plugins.authz.v1.StringList
	0,  // 1: workflow.plugins.authz.v1.CasbinModuleConfig.role_assignments:type_name -> workflow.plugins.authz.v1.StringList
	1,  // 2: workflow.plugins.authz.v1.CasbinModuleConfig.adapter:type_name -> workflow.plugins.authz.v1.AdapterConfig
	2,  // 3: workflow.plugins.authz.v1.CasbinModuleConfig.watcher:type_name -> workflow.plugins.authz.v1.WatcherConfig
	5,  // 4: workflow.plugins.authz.v1.AuthzCheckConfig.extra_fields:type_name -> workflow.plugins.authz.v1.ExtraField
	5,  // 5: workflow.plugins.authz.v1.AuthzCheckInput.extra_fields:type_name -> workflow.plugins.authz.v1.ExtraField
	29, // 6: workflow.plugins.authz.v1.AuthzCheckOutput.response_headers:type_name -> google.protobuf.Struct
	0,  // 7: workflow.plugins.authz.v1.RoleAssignConfig.assignments:type_name -> workflow.plugins.authz.v1.StringList
	0,  // 8: workflow.plugins.authz.v1.RoleAssignInput.assignments:type_name -> workflow.plugins.authz.v1.StringList
	0,  // 9: workflow.plugins.authz.v1.RoleAssignOutput.assignments:type_name -> workflow.plugins.authz.v1.StringList
	29, // 10: workflow.plugins.authz.v1.GenericStepOutput.output:type_name -> google.protobuf.Struct
	29, // 11: workflow.plugins.authz.v1.PermitStepConfig.values:type_name -> google.protobuf.Struct
	29, // 12: workflow.plugins.authz.v1.PermitStepInput.values:type_name -> google.protobuf.Struct
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_internal_contracts_authz_proto_init() }
func file_internal_contracts_authz_proto_init() {
	if File_internal_contracts_authz_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_contracts_authz_proto_rawDesc), len(file_internal_contracts_authz_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_contracts_authz_proto_goTypes,
		DependencyIndexes: file_internal_contracts_authz_proto_depIdxs,
		MessageInfos:      file_internal_contracts_authz_proto_msgTypes,
	}.Build()
	File_internal_contracts_authz_proto = out.File
	file_internal_contracts_authz_proto_goTypes = nil
	file_internal_contracts_authz_proto_depIdxs = nil
}
